name: mvn clean compile

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  encryption:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Running tests
        run: mvn -B clean compile test